# Generated by Django 5.1 on 2025-06-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_old_price_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
